= kafkakitty

Kafkakitty is a kafkacat-inspired utility which brings Kafka messages to your
browser in real-time.

== Running

Kafkakitty uses similar arguments to
link:https://github.com/edenhill/kafkacat[kafkacat], but does not have full
parity. To run against a locally running Kafka service, use the following
invocation:

[source,bash]
----
% kafkakitty -t my-topic
----

This will automatically open a browser to
link:http://localhost:8000[localhost:8000], which is where the Kafkakitty
interface can be found.


[source,bash]
----
Kafkakitty 😿 0.2.0
A cute little Kafka consumer

USAGE:
    kafkakitty [FLAGS] [OPTIONS] --topics <topics>...

FLAGS:
    -h, --help       Prints help information
    -n, --no-open    Disable opening a browser window automatically
    -V, --version    Prints version information

OPTIONS:
    -b, --brokers <brokers>      Broker list in kafka format [default: localhost:9092]
    -G, --group-id <group-id>    Consumer group ID for Kafka [default: kafkakitty]
    -X <settings>...             Set a librdkafka configuration property
    -t, --topics <topics>...     List of topics to follow
----


=== Configuration

For the various additional properties which can be set through the `-X`
command-line argument, the
link:https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md[librdkafka
configuration] documents the possible options.


[NOTE]
====
Kafkakitty does *not* come with any built-in security, which means that all
users on the machine will be able to view the locally hosted server.
====


== Hacking

Kafkakitty is really composed of two related parts:

. A link:https://rocket.rs[Rocket]-based webserver written in Rust.
. The GUI written in link:https://vuejs.org[Vue.js].

Because of this it is important to have both Rust and Node installed in your
development environment.

=== Frontend

. Install the Node packages with `npm install`
. Build the frontend: `npm run build`

In order to rapidly prototype the frontend, it can be helpful to run the
backend (see below) and then spin up a dynamically reloading frontend server
with `npm run dev`. Once the dev server is online, it should be available at
link:http://localhost:8080[localhost:8080] and _should_ reload assets as the
Vue components are changed.

=== Backend

It is usually best to build the backend only after building the frontend, since the backend build will include assets generated by the frontend build process.

. Build the Rust application with `cargo build`
. Run the backend with `cargo run -- -t my-topic`

[TIP]
====
Install the `cargo-watch` crate to automatically rebuild the backend when files
have changed!
====

